export const Products = [
  {
    id: 'mobilisco',
    page: '/mobilisco',
    title: 'MobiliSCO 8.2.1',
    formUrl: 'https://docs.google.com/forms/d/1NmOvwDBvewcF_F68_tsugW_jv_4_5aX98mVk-bajzdY/formResponse?entry.162101201=',
    downloadUrl: '/static/files/MobiliSCO_V8-2-1.zip',
    tagline: 'Les voyages scolaires cessent d’être un enfer',
    description: 'Un logiciel de gestion de vos voyages scolaires, depuis l’inscription des élèves jusqu’au bilan financier',
    imageSource: '/static/arrow.png',
    color: '#24b47e',
    background: '',
    mapUrl: 'https://www.google.com/maps/d/embed?mid=1J9u0GSjmOsuFyvRc_n40MIeOaOI',
    salesPoints: [
      'Inscription des élèves aux voyages et édition des lettres d\'engagement des familles',
      'Edition des budgets, bilan financier, justificatif des ordres de recettes et documents en tout genre',
      'Suivi des encaissements par transfert dans GFC',
    ],
    externalLinks: [
      {
        icon: '/static/icon-forum.png',
        label: 'Forum',
        href: 'https://gestionnaires.actifforum.com/t44015-mobilisco',
      },
      {
        icon: '/static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://tube-numerique-educatif.apps.education.fr/c/andre_etienne_channel/videos',
      },
    ],
  },
  {
    id: 'gemasco',
    page: '/gemasco',
    title: 'GemaSCO 4.2.2',
    formUrl: 'https://docs.google.com/forms/d/1AcTYcJrqYufC7N8SUeWzC1EpID0kprPHjTNq8Z5JOuk/formResponse?entry.1936573090=',
    emailEntryRef: '843103382',
    pageEntryRef: '89190430',
    downloadUrl: '/static/files/GemaSCO_v4-2-2.zip',
    tagline: 'L’appli qui gère les manuels scolaires',
    description: 'GemaSCO commande, distribue, récupère et fait même l’inventaire de vos manuels scolaires !',
    imageSource: '/static/book.png',
    color: '#ff7b19',
    background: '',
    mapUrl: 'https://www.google.com/maps/d/embed?mid=1CHokoocxSwzJOq16GsTOv4Ypono',
    salesPoints: [
      'Création d\'étiquettes code-barre à coller sur les manuels scolaires',
      'Prêt et retour automatisé',
      'Suivi du stock en temps réel',
      'Edition d\'avis aux familles des livres non-rendus ou dégradés',
      'Déterminer à tout moment à qui appartient n\'importe quel livre',
    ],
    externalLinks: [
      {
        icon: '/static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://tube-numerique-educatif.apps.education.fr/c/andre_etienne_channel/videos',
      },
      {
        icon: '/static/icon-forum.png',
        label: 'Forum',
        href: 'https://gestionnaires.actifforum.com/t43041-gemasco-4',
      },
    ],
  },
  {
    id: 'trombinosco',
    page: '/trombinosco',
    title: 'TrombinoSCO 3.2.0',
    formUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfhktm15pCKM8UK3_W-CUYFKU2a8R4lsmW6IBAFTVCI5LAYng/formResponse?entry.1297664213=',
    emailEntryRef: '1806504359',
    pageEntryRef: '201096845',
    downloadUrl: '/static/files/TrombinoSCO_3-2-0.zip',
    tagline: 'Les photos des élèves avec le sourire',
    description: 'Un logiciel de gestion des photos, qui génère facilement les cartes de lycéen ou les trombinoscopes',
    imageSource: '/static/logotrombi.png',
    color: '#a31390',
    background: '',
    mapUrl: 'https://www.google.com/maps/d/embed?mid=1Jfi6lLgHjqiQ-C92aeyFbHius3mbFxB7',
    salesPoints: [
      'Pilote l\'imprimante à badges pour générer des cartes de lycéen infalsifiables',
      'Fournit des trombinoscopes pour n\'importe quel groupe pédagogique d\'après les enseignements signalés dans SIECLE',
      'Permet des impressions sur autocollants pour le dépannage',
    ],
    externalLinks: [
            {
        icon: '/static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://tube-numerique-educatif.apps.education.fr/c/andre_etienne_channel/videos',
      },
      {
        icon: '/static/icon-forum.png',
        label: 'Forum',
        href: 'https://gestionnaires.actifforum.com/t35786-trombinosco',
      },
    ],
  },
    {
    id: 'cedisco',
    page: '/cedisco',
    title: 'CédiSCO 2.0.3',
    formUrl: 'https://docs.google.com/forms/d/1AcTYcJrqYufC7N8SUeWzC1EpID0kprPHjTNq8Z5JOuk/formResponse?entry.1936573090=',
    emailEntryRef: '843103382',
    pageEntryRef: '89190430',
    downloadUrl: '/static/files/CédiSCO-2-0-3.zip',
    tagline: 'Les conseils de discipline sans souci de procédure',
    description: 'CédiSCO assure l\'ensemble du travail de procédure pour le conseil de discipline, sans risque d\'erreur et sans effort.',
    imageSource: '/static/balance.png',
    color: '#c40207',
    background: '',
    mapUrl: 'https://www.google.com/maps/d/embed?mid=1CHokoocxSwzJOq16GsTOv4Ypono',
    salesPoints: [
      'Edition des convocations pour l\'élève, sa famille, les membres du conseil et les témoins',
      'Conducteur de procédure pour le président de séance',
      'Secrétariat de séance semi-automatique en temps réel',
      'Procès-verbal et notification immédiats',
      'Registre des sanctions de l\'EPLE',
    ],
    externalLinks: [
      {
        icon: '/static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://tube-numerique-educatif.apps.education.fr/c/andre_etienne_channel/videos',
      },
      {
        icon: '/static/icon-forum.png',
        label: 'Forum',
        href: 'https://gestionnaires.actifforum.com/t43048-cedisco',
      },
     ],
    },
   {
    id: 'effesco',
    page: '/effesco',
    title: 'EffeSCO 2.0.0',
    formUrl: 'https://docs.google.com/forms/d/1NmOvwDBvewcF_F68_tsugW_jv_4_5aX98mVk-bajzdY/formResponse?entry.162101201=',
    downloadUrl: '/static/files/EffeSCO_2-0-0.zip',
    tagline: 'Les aides sociales enfin faciles et rapides',
    description: 'Un logiciel de gestion du fonds social, depuis les demandes pré-remplies jusqu\’à la pièce justificative comptable',
    imageSource: '/static/blue_handshake.png',
    color: '#0a938f',
    background: '',
    salesPoints: [
      'Application sécurisée (le mdp par défaut est : dada)',
      'Formulaires de demande d\'aide pré-remplis',
      'Acte du CA pour les modalités de l\'aide puis compte-rendu annuel d\'activité',
      'Pré-calcul des montants attribués, suivi des financements disponibles, pièces justificatives comptables',
    ],
    externalLinks: [
      {
        icon: '/static/icon-forum.png',
        label: 'Forum',
        href: 'https://gestionnaires.actifforum.com/t48185-effesco',
      },
      {
        icon: '/static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://tube-numerique-educatif.apps.education.fr/c/andre_etienne_channel/videos',
      },
    ],
  },
   {
    id: 'essatedesco',
    page: '/essatedesco',
    title: 'EssatédéSCO 2.0.5',
    formUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfhktm15pCKM8UK3_W-CUYFKU2a8R4lsmW6IBAFTVCI5LAYng/formResponse?entry.1297664213=',
    downloadUrl: '/static/files/EssatedeSCO_2-0-5.zip',
    tagline: 'La saisie administrative à tiers détenteur à la portée des comptables d\'EPLE',
    description: 'Tous les documents, toutes les procédures, sans effort et sans risque',
    imageSource: '/static/EssatedeSCOminitrs.png',
    color: '#0a938f',
    background: '',
    salesPoints: [
      'Gère tous les établissements d\'une agence comptable',
      'Importe des créances de Op@le, GFC, Cocwinelle (pour l\'instant) et permet d\'en ajouter manuellement',
      'Fournit sans effort les documents SATD (employeur ou banque), FICOBA, huissier...',
    ],
    externalLinks: [
      {
        icon: '/static/icon-forum.png',
        label: 'Forum',
        href: 'https://gestionnaires.actifforum.com/t39615-essatedesco',
      },
      {
        icon: '/static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://tube-numerique-educatif.apps.education.fr/c/andre_etienne_channel/videos',
      },
    ],
  },
   {
    id: 'ribsco',
    page: '/ribsco',
    title: 'RibSCO 1.6',
    downloadUrl: '/static/files/RibSCO_1-6.zip',
    tagline: 'Vérifiez vos fichiers de paiement en un clin d\'oeil',
    description: 'Soumettez vos fichiers XML de règlement ou de prélèvement à RibSCO et vous saurez immédiatement s\'ils contiennent une erreur',
    imageSource: '/static/RibSCO_CCBY_ParkJisun.png',
    color: '#24b47e',
    background: '',
    salesPoints: [
      'Téléchargez et ouvrez l\'application',
      'Soumettez un fichier XML',
      'Rapport immédiat sur toute anomalie détectée dans les coordonnées bancaires',
    ],
    externalLinks: [
      {
        icon: '/static/icon-forum.png',
        label: 'Forum',
        href: 'https://gestionnaires.actifforum.com/t41662-ribsco',
      },
      {
        icon: '/static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://tube-numerique-educatif.apps.education.fr/c/andre_etienne_channel/videos',
      },
    ],
  },
  {
    id: 'emaintenance',
    page: '/emaintenance',
    title: 'AJI-maintenance',
    tagline: 'Réparer n\'est plus un problème',
    description: 'L\'appli AJI-maintenance permet l\'entretien et la gestion de tout type de matériel au sein d\'un établissement, de l\'ampoule grillée au rétroprojecteur en panne.',
    imageSource: '/static/wrench.png',
    color: '#7dd2c2',
    background: '',
    mapUrl: 'https://www.google.com/maps/d/embed?mid=1CHokoocxSwzJOq16GsTOv4Ypono',
  },
  {
    id: 'votre-projet',
    page: '/votre-projet',
    title: 'Votre projet',
    tagline: 'L’open académicien, c’est vous',
    description: 'Vous voulez moderniser votre profession ? Vous avez une idée que vous aimeriez développer et pour laquelle vous êtes prêt à vous investir ? Contactez-nous ! On vous attendait.',
    imageSource: '/static/lamp.png',
    color: '#ffd966',
    background: '/static/votre-projet.jpg',
  },
]

export const Colors = {
  primary: '#26a69a',
}
